
import { CompanySettings, Translations, ThemeSettings, GlobalNotification, AdminGeneralSettings } from './types';

export const DEFAULT_SETTINGS: CompanySettings = {
  name: "Your Company Name",
  logo: "",
  email: "contact@company.com",
  phone: "+212 600 000 000",
  address: "123 Business Street, Casablanca, Morocco",
  ice: "001234567000089",
  iff: "12345678",
  rc: "Casablanca 12345",
  defaultTaxRate: 20,
  defaultCurrency: 'MAD',
  businessType: 'company',
  autoEntrepreneurType: 'services',
  invoiceNumberPrefix: 'INV-{YEAR}-',
  defaultNotes: 'Merci pour votre confiance.',
  mail: {
    host: '',
    port: 587,
    user: '',
    pass: '',
    encryption: 'tls',
  },
};

export const DEFAULT_THEME_SETTINGS: ThemeSettings = {
    primaryColor: '#4f46e5', // default indigo-600
    logo: '',
    favicon: '',
    colorMode: 'system',
    fontFamily: 'Poppins',
    borderRadius: 'lg',
    layoutDensity: 'comfortable',
};

export const DEFAULT_GLOBAL_NOTIFICATION: GlobalNotification = {
    id: 'default-notification',
    message: '',
    isActive: false,
};

export const DEFAULT_ADMIN_SETTINGS: AdminGeneralSettings = {
  registration: {
    allowRegistration: true,
    initialCredits: 5,
  },
  defaultInvoice: {
    currency: 'MAD',
    taxRate: 20,
  },
  mail: {
    host: 'smtp.example.com',
    port: 587,
    user: 'user@example.com',
    pass: '',
    encryption: 'tls',
  },
};


export const TRANSLATIONS: { [lang: string]: Translations } = {
  fr: {
    // App translations from before
    dashboard: "Tableau de Bord",
    analytics: "Analyses",
    invoices: "Factures",
    settings: "Paramètres",
    newInvoice: "Nouvelle Facture",
    totalInvoices: "Factures Totales",
    paid: "Payées",
    unpaid: "Impayées",
    totalRevenue: "Revenu Total",
    invoiceNumber: "N° de Facture",
    customer: "Client",
    issueDate: "Date d'émission",
    dueDate: "Date d'échéance",
    amount: "Montant",
    status: "Statut",
    actions: "Actions",
    view: "Voir",
    edit: "Modifier",
    delete: "Supprimer",
    draft: "Brouillon",
    sent: "Envoyée",
    overdue: "En retard",
    createInvoice: "Créer une Facture",
    editInvoice: "Modifier la Facture",
    billTo: "Facturer à",
    customerName: "Nom du client",
    customerEmail: "Email du client",
    customerPhone: "Téléphone du client",
    customerAddress: "Adresse du client",
    customerCin: "CIN du client",
    customerIce: "ICE du client",
    invoiceDetails: "Détails de la facture",
    currency: "Devise",
    status_draft: "Brouillon",
    status_sent: "Envoyée",
    status_paid: "Payée",
    status_overdue: "En retard",
    items: "Articles",
    description: "Description",
    quantity: "Qté",
    price: "Prix",
    tax: "Taxe (%)",
    total: "Total",
    addItem: "Ajouter un article",
    subtotal: "Sous-total",
    taxAmount: "Montant de la taxe",
    grandTotal: "Total Général",
    notes: "Notes",
    saveInvoice: "Enregistrer la facture",
    companySettings: "Paramètres de l'entreprise",
    companyName: "Nom de l'entreprise",
    companyLogo: "Logo de l'entreprise",
    changeLogo: "Changer",
    removeLogo: "Supprimer",
    companyEmail: "Email de l'entreprise",
    companyPhone: "Téléphone de l'entreprise",
    companyAddress: "Adresse de l'entreprise",
    companyIce: "ICE",
    companyIf: "IF",
    companyRc: "RC",
    defaultTaxRate: "Taux de TVA par défaut (%)",
    saveSettings: "Enregistrer les paramètres",
    settingsSaved: "Paramètres enregistrés avec succès!",
    invoice: "FACTURE",
    downloadPdf: "Télécharger en PDF",
    print: "Imprimer",
    sendByEmail: "Envoyer par Email",
    from: "De",
    to: "À",
    paymentDetails: "Détails de paiement",
    bankName: "Nom de la banque",
    accountNumber: "Numéro de compte",
    generateWithAI: "Générer avec l'IA",
    generating: "Génération...",
    invoiceEmailSubject: "Sujet de l'email de la facture",
    invoiceEmailBody: "Corps de l'email de la facture",
    sendEmail: "Envoyer l'email",
    emailSentSuccess: "Email envoyé avec succès (simulation).",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer cette facture?",
    cancel: "Annuler",
    confirm: "Confirmer",
    logout: "Déconnexion",
    email: "Email",
    password: "Mot de passe",
    loginToYourAccount: "Connectez-vous à votre compte",
    dontHaveAccount: "Vous n'avez pas de compte?",
    createAccount: "Créez votre compte",
    alreadyHaveAccount: "Vous avez déjà un compte?",
    credits: "Crédits",
    buyCredits: "Acheter des Crédits",
    noCreditsMessage: "Vous n'avez plus de crédits. Veuillez en acheter pour créer une nouvelle facture.",
    invoiceCost: "Chaque nouvelle facture coûte 1 crédit (2 DH).",
    adminPanel: "Panneau d'administration",
    manageUsers: "Gérer les utilisateurs",
    addCredits: "Ajouter des crédits",
    creditsAdded: "Crédits ajoutés.",
    welcome: "Bienvenue",
    userExists: "L'utilisateur existe déjà.",
    registrationDisabled: "L'inscription est actuellement désactivée.",
    invalidCredentials: "Identifiants invalides.",
    
    // Registration v2
    fullName: "Nom complet",
    phoneNumber: "Numéro de téléphone",

    // User Settings v2
    profileSettings: "Paramètres du Profil",
    profilePhoto: "Photo de profil",
    passwordSettings: "Changer le mot de passe",
    saveProfile: "Enregistrer le profil",
    userProfileUpdated: "Profil mis à jour avec succès!",
    mailSettings: "Paramètres E-mail (SMTP)",

    // Client Management
    clients: "Clients",
    newClient: "Nouveau Client",
    editClient: "Modifier le Client",
    addClient: "Ajouter un client",
    saveClient: "Enregistrer le client",
    clientList: "Liste des clients",
    noClientsMessage: "Aucun client à afficher.",
    confirmDeleteClient: "Êtes-vous sûr de vouloir supprimer ce client?",
    clientName: "Nom du client",
    clientEmail: "Email du client",
    clientPhone: "Téléphone du client",
    clientAddress: "Adresse du client",
    clientCin: "CIN du client",
    clientIce: "ICE du client",
    selectClient: "Sélectionner un client",
    viewPortal: "Voir le portail",

    // Landing Page & Header
    home_nav: "Accueil",
    features: "Fonctionnalités",
    pricing: "Tarifs",
    login: "Connexion",
    register: "S'inscrire",
    getStarted: "Commencer gratuitement",
    heroTitle: "La facturation simplifiée pour les entreprises au Maroc",
    heroSubtitle: "Créez, envoyez et gérez des factures professionnelles conformes à la législation marocaine. Gagnez du temps et soyez payé plus rapidement.",
    feature1Title: "Conformité Marocaine",
    feature1Desc: "Générez des factures avec tous les champs obligatoires: ICE, IF, RC, et une gestion de la TVA à 20% (modifiable).",
    feature2Title: "Entièrement Bilingue",
    feature2Desc: "Interface disponible en Français et en Arabe, avec un support complet du mode RTL pour une expérience native.",
    feature3Title: "PDF Professionnels",
    feature3Desc: "Téléchargez et envoyez des factures au format PDF avec un design soigné, prêtes pour l'impression ou l'envoi par email.",
    feature4Title: "Assistance par IA",
    feature4Desc: "Utilisez l'intelligence artificielle pour générer automatiquement des descriptions de services ou des corps d'e-mail.",
    feature5Title: "Gestion des Clients",
    feature5Desc: "Sauvegardez les informations de vos clients pour les réutiliser facilement dans vos futures factures.",
    feature6Title: "Tableau de Bord Intuitif",
    feature6Desc: "Suivez vos revenus, vos factures payées et impayées en un clin d'œil.",
    pricingTitle: "Une tarification simple et transparente",
    pricingSubtitle: "Pas d'abonnement mensuel. Payez uniquement pour ce que vous utilisez.",
    pricingCardTitle: "Pay-Per-Invoice",
    pricingCardPrice: "1 Crédit / Facture",
    pricingCardPriceDetail: "(~2 MAD)",
    pricingFeature1: "5 crédits offerts à l'inscription",
    pricingFeature2: "Pas de frais cachés",
    pricingFeature3: "Achetez des crédits au besoin",
    pricingFeature4: "Toutes les fonctionnalités incluses",
    ctaTitle: "Prêt à simplifier votre facturation ?",
    ctaSubtitle: "Créez un compte et envoyez votre première facture en quelques minutes.",
    footerText: "© 2024 Invoice.ma. Tous droits réservés. Un outil conçu pour les entrepreneurs marocains.",
    
    // Legal
    termsOfService: "Conditions d'utilisation",
    privacyPolicy: "Politique de confidentialité",
    termsTitle: "Conditions d'utilisation",
    termsContent: `<p>Dernière mise à jour : [Date]</p><p>Bienvenue sur Invoice.ma. En utilisant notre service, vous acceptez ces conditions. Veuillez les lire attentivement.</p><strong>1. Utilisation du Service</strong><p>Vous devez suivre toutes les politiques mises à votre disposition dans le Service. N'utilisez pas nos Services de manière abusive. Vous ne pouvez utiliser nos Services que conformément à la loi.</p><strong>2. Votre Compte Invoice.ma</strong><p>Pour protéger votre compte, gardez votre mot de passe confidentiel. Vous êtes responsable de l'activité qui se produit sur ou via votre compte.</p><strong>3. Modifications et Résiliation de nos Services</strong><p>Nous modifions et améliorons constamment nos Services. Nous pouvons ajouter ou supprimer des fonctionnalités ou des caractéristiques, et nous pouvons suspendre ou arrêter complètement un Service.</p>`,
    privacyTitle: "Politique de confidentialité",
    privacyContent: `<p>Dernière mise à jour : [Date]</p><p>Cette politique de confidentialité explique comment Invoice.ma collecte, utilise et protège vos informations personnelles.</p><strong>1. Informations que nous collectons</strong><p>Nous collectons les informations que vous nous fournissez directement, telles que les informations de votre compte et les détails de facturation que vous créez. Nous utilisons le stockage local de votre navigateur pour conserver vos données ; aucune donnée de facture n'est envoyée à nos serveurs.</p><strong>2. Comment nous utilisons les informations</strong><p>Nous utilisons les informations que nous collectons pour fournir, maintenir et améliorer nos services.</p><strong>3. Partage d'informations</strong><p>Nous ne partageons pas vos informations personnelles avec des entreprises, des organisations ou des individus en dehors de Invoice.ma.</p>`,

    // WhatsApp
    sendByWhatsApp: "Envoyer par WhatsApp",
    whatsAppModalTitle: "Partager la facture via WhatsApp",
    whatsAppMessage: "Message pour WhatsApp",
    clientPhoneNumber: "Numéro de téléphone du client",
    whatsAppMessageTemplate: "Bonjour {clientName},\n\nVoici un lien pour consulter votre facture {invoiceNumber} d'un montant de {totalAmount}.\n\n{invoiceLink}\n\nCordialement,\n{companyName}",
    send: "Envoyer",

    // Admin Panel v2
    admin_dashboard: "Admin Dashboard",
    admin_users: "Utilisateurs",
    admin_appearance: "Apparence",
    admin_notifications: "Notifications",
    admin_settings: "Réglages Généraux",
    admin_security: "Sécurité",
    totalUsers: "Utilisateurs Totaux",
    totalCreditsDistributed: "Crédits Distribués",
    customizeAppearance: "Personnaliser l'apparence",
    primaryColor: "Couleur Principale",
    appLogo: "Logo de l'application",
    saveChanges: "Enregistrer les modifications",
    globalNotification: "Notification Globale",
    notificationMessage: "Message de notification",
    notificationStatus: "Statut de la notification",
    active: "Active",
    inactive: "Inactive",
    updateNotification: "Mettre à jour la notification",
    
    // Admin Security
    changeAdminPassword: "Changer le mot de passe admin",
    newPassword: "Nouveau mot de passe",
    confirmNewPassword: "Confirmer le nouveau mot de passe",
    passwordChangedSuccess: "Mot de passe changé avec succès !",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas.",

    // Admin General Settings
    userRegistration: "Inscription des utilisateurs",
    allowNewRegistrations: "Autoriser les nouvelles inscriptions",
    enabled: "Activé",
    disabled: "Désactivé",
    initialCreditsForNewUsers: "Crédits initiaux pour les nouveaux utilisateurs",
    defaultInvoiceSettings: "Paramètres de facture par défaut",
    defaultCurrency: "Devise par défaut",
    smtpHost: "Hôte SMTP",
    smtpPort: "Port SMTP",
    smtpUser: "Utilisateur SMTP",
    smtpPassword: "Mot de passe SMTP",
    smtpEncryption: "Chiffrement",

    // Admin Appearance v2
    advancedAppearanceSettings: "Paramètres d'apparence avancés",
    colorMode: "Mode de couleur",
    light: "Clair",
    dark: "Sombre",
    system: "Système",
    fontFamily: "Police de caractères",
    borderRadius: "Rayon de bordure",
    radius_none: "Aucun",
    radius_sm: "Petit",
    radius_md: "Moyen",
    radius_lg: "Grand",
    favicon: "Favicon",
    layoutDensity: "Densité de la mise en page",
    density_comfortable: "Confortable",
    density_compact: "Compacte",

    // Invoice Edit cost
    editCostFree: "Votre première modification pour cette facture est gratuite.",
    editCostCharged: "Cette modification coûtera 1 crédit. Vous avez {credits} crédits restants.",
    editFailedNoCredits: "Vous n'avez pas assez de crédits pour enregistrer ces modifications. Veuillez en acheter.",
    invoiceNumberReadonly: "Le numéro de facture ne peut être modifié après sa création pour garantir l'intégrité des dossiers.",
    
    // Feature Set 1: Analytics
    cashFlowForecast: "Prévision de Trésorerie",
    timeframe: "Période",
    next30days: "30 prochains jours",
    next60days: "60 prochains jours",
    next90days: "90 prochains jours",
    projectedIncome: "Revenu projeté",
    noUpcomingIncome: "Aucun revenu à projeter pour la période sélectionnée.",
    tvaCollectionReport: "Rapport de Collecte TVA",
    selectPeriod: "Sélectionner une période",
    startDate: "Date de début",
    endDate: "Date de fin",
    totalInvoicedTVA: "TVA Facturée Totale",
    totalCollectedTVA: "TVA Collectée Totale",
    performanceDashboard: "Tableau de Bord de Performance",
    topClients: "Meilleurs Clients",
    topProductsServices: "Meilleurs Produits/Services",
    clientPaymentHabits: "Habitudes de Paiement des Clients",
    avgPaymentDays: "Jours de paiement moy.",
    daysLate: "jours de retard",
    paidOnTime: "Payé à temps",
    paidEarly: "jours en avance",
    noData: "Pas de données disponibles.",
    serviceDescription: "Description du service",

    // Feature Set 2: Client Portal & Multi-currency
    clientPortal: "Portail Client",
    accountStatement: "Relevé de Compte",
    outstandingBalance: "Solde impayé",
    payNow: "Payer Maintenant",
    sendMessage: "Envoyer un message",
    messageSentSuccess: "Message envoyé avec succès!",
    typeYourMessage: "Tapez votre message ici...",
    totalInvoices_portal: "Factures Totales",
    totalPaid_portal: "Total Payé",
    exchangeRate: "Taux de change",
    exchangeRateNote: "Taux de change ({from}/{to}) du {date}: {rate}",

    // Auto-entrepreneur & TVA Declaration
    businessProfile: "Profil de l'entreprise",
    businessType: "Type d'entreprise",
    type_company: "Société",
    "type_auto-entrepreneur": "Auto-entrepreneur",
    autoEntrepreneurType: "Type d'activité (AE)",
    ae_services: "Prestations de services",
    ae_industrial: "Activités industrielles",
    ae_commercial: "Activités commerciales",
    ae_artisanal: "Activités artisanales",
    aeRevenueTracker: "Suivi du Chiffre d'Affaires (AE)",
    annualRevenue: "Chiffre d'affaires annuel (encaissé)",
    revenueCap: "Plafond",
    tvaNotApplicable: "TVA non applicable - article 293 B du CGI",
    invoiceCustomization: "Personnalisation des Factures",
    invoiceNumberPrefix: "Préfixe du numéro de facture",
    invoicePrefixPlaceholder: "ex: FACT-{YEAR}-",
    defaultInvoiceNotes: "Notes par défaut sur la facture",
    tvaDeclaration: "Déclaration TVA",
    exportSalesReport: "Exporter Rapport des Ventes (CSV)",
    exportCollectionsReport: "Exporter Rapport des Encaissements (CSV)",
    
    // Admin User Edit
    editUserTitle: "Modifier l'utilisateur",
    userSettings: "Paramètres de l'utilisateur",
    resetUserPassword: "Réinitialiser le mot de passe",
    resetPasswordConfirmation: "Êtes-vous sûr de vouloir réinitialiser le mot de passe de cet utilisateur ? Un nouveau mot de passe temporaire sera généré.",
    passwordResetSuccess: "Le mot de passe de l'utilisateur a été réinitialisé à 'password123'.",

  },
  ar: {
    // App translations from before
    dashboard: "لوحة التحكم",
    analytics: "التحليلات",
    invoices: "الفواتير",
    settings: "الإعدادات",
    newInvoice: "فاتورة جديدة",
    totalInvoices: "مجموع الفواتير",
    paid: "مدفوعة",
    unpaid: "غير مدفوعة",
    totalRevenue: "إجمالي الدخل",
    invoiceNumber: "رقم الفاتورة",
    customer: "العميل",
    issueDate: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    amount: "المبلغ",
    status: "الحالة",
    actions: "إجراءات",
    view: "عرض",
    edit: "تعديل",
    delete: "حذف",
    draft: "مسودة",
    sent: "مرسلة",
    overdue: "متأخرة",
    createInvoice: "إنشاء فاتورة",
    editInvoice: "تعديل الفاتورة",
    billTo: "فوترة إلى",
    customerName: "اسم العميل",
    customerEmail: "البريد الإلكتروني للعميل",
    customerPhone: "هاتف العميل",
    customerAddress: "عنوان العميل",
    customerCin: "البطاقة الوطنية للعميل",
    customerIce: "ICE العميل",
    invoiceDetails: "تفاصيل الفاتورة",
    currency: "العملة",
    status_draft: "مسودة",
    status_sent: "مرسلة",
    status_paid: "مدفوعة",
    status_overdue: "متأخرة",
    items: "البنود",
    description: "الوصف",
    quantity: "الكمية",
    price: "السعر",
    tax: "الضريبة (%)",
    total: "المجموع",
    addItem: "إضافة بند",
    subtotal: "المجموع الفرعي",
    taxAmount: "قيمة الضريبة",
    grandTotal: "المجموع الكلي",
    notes: "ملاحظات",
    saveInvoice: "حفظ الفاتورة",
    companySettings: "إعدادات الشركة",
    companyName: "اسم الشركة",
    companyLogo: "شعار الشركة",
    changeLogo: "تغيير",
    removeLogo: "إزالة",
    companyEmail: "البريد الإلكتروني للشركة",
    companyPhone: "هاتف الشركة",
    companyAddress: "عنوان الشركة",
    companyIce: "ICE",
    companyIf: "IF",
    companyRc: "RC",
    defaultTaxRate: "نسبة الضريبة الافتراضية (%)",
    saveSettings: "حفظ الإعدادات",
    settingsSaved: "تم حفظ الإعدادات بنجاح!",
    invoice: "فاتورة",
    downloadPdf: "تحميل PDF",
    print: "طباعة",
    sendByEmail: "إرسال بالبريد الإلكتروني",
    from: "من",
    to: "إلى",
    paymentDetails: "تفاصيل الدفع",
    bankName: "اسم البنك",
    accountNumber: "رقم الحساب",
    generateWithAI: "إنشاء بواسطة الذكاء الاصطناعي",
    generating: "جاري الإنشاء...",
    invoiceEmailSubject: "موضوع بريد الفاتورة الإلكتروني",
    invoiceEmailBody: "محتوى بريد الفاتورة الإلكتروني",
    sendEmail: "إرسال البريد الإلكتروني",
    emailSentSuccess: "تم إرسال البريد الإلكتروني بنجاح (محاكاة).",
    confirmDelete: "هل أنت متأكد من رغبتك في حذف هذه الفاتورة؟",
    cancel: "إلغاء",
    confirm: "تأكيد",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    loginToYourAccount: "تسجيل الدخول إلى حسابك",
    dontHaveAccount: "ليس لديك حساب؟",
    createAccount: "أنشئ حسابك",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    credits: "الأرصدة",
    buyCredits: "شراء الأرصدة",
    noCreditsMessage: "لقد نفدت أرصدتك. يرجى شراء المزيد لإنشاء فاتورة جديدة.",
    invoiceCost: "كل فاتورة جديدة تكلف رصيدًا واحدًا (2 درهم).",
    adminPanel: "لوحة الإدارة",
    manageUsers: "إدارة المستخدمين",
    addCredits: "إضافة أرصدة",
    creditsAdded: "تمت إضافة الأرصدة.",
    welcome: "أهلاً بك",
    userExists: "هذا المستخدم موجود بالفعل.",
    registrationDisabled: "التسجيل مغلق حالياً.",
    invalidCredentials: "بيانات الاعتماد غير صالحة.",

    // Registration v2
    fullName: "الاسم الكامل",
    phoneNumber: "رقم الهاتف",

    // User Settings v2
    profileSettings: "إعدادات الملف الشخصي",
    profilePhoto: "الصورة الشخصية",
    passwordSettings: "تغيير كلمة المرور",
    saveProfile: "حفظ الملف الشخصي",
    userProfileUpdated: "تم تحديث الملف الشخصي بنجاح!",
    mailSettings: "إعدادات البريد (SMTP)",

    // Client Management
    clients: "العملاء",
    newClient: "عميل جديد",
    editClient: "تعديل العميل",
    addClient: "إضافة عميل",
    saveClient: "حفظ العميل",
    clientList: "قائمة العملاء",
    noClientsMessage: "لا يوجد عملاء لعرضهم.",
    confirmDeleteClient: "هل أنت متأكد من رغبتك في حذف هذا العميل؟",
    clientName: "اسم العميل",
    clientEmail: "البريد الإلكتروني للعميل",
    clientPhone: "هاتف العميل",
    clientAddress: "عنوان العميل",
    clientCin: "البطاقة الوطنية للعميل",
    clientIce: "ICE العميل",
    selectClient: "اختر عميل",
    viewPortal: "عرض البوابة",

    // Landing Page & Header
    home_nav: "الرئيسية",
    features: "المميزات",
    pricing: "الأسعار",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    getStarted: "ابدأ مجانًا",
    heroTitle: "نظام الفوترة المبسط للشركات في المغرب",
    heroSubtitle: "أنشئ وأرسل وأدر فواتير احترافية متوافقة مع القوانين المغربية. وفر الوقت واحصل على أموالك بشكل أسرع.",
    feature1Title: "مطابقة للقانون المغربي",
    feature1Desc: "أصدر فواتير تحتوي على جميع الحقول الإلزامية: ICE، IF، RC، مع إدارة ضريبة القيمة المضافة بنسبة 20% (قابلة للتعديل).",
    feature2Title: "ثنائي اللغة بالكامل",
    feature2Desc: "واجهة متوفرة باللغتين الفرنسية والعربية، مع دعم كامل لنمط RTL لتجربة استخدام أصلية.",
    feature3Title: "ملفات PDF احترافية",
    feature3Desc: "حمّل وأرسل فواتير بتنسيق PDF بتصميم أنيق، جاهزة للطباعة أو الإرسال عبر البريد الإلكتروني.",
    feature4Title: "مساعدة بالذكاء الاصطناعي",
    feature4Desc: "استخدم الذكاء الاصطناعي لإنشاء أوصاف الخدمات أو محتوى رسائل البريد الإلكتروني تلقائيًا.",
    feature5Title: "إدارة العملاء",
    feature5Desc: "احفظ معلومات عملائك لإعادة استخدامها بسهولة في فواتيرك المستقبلية.",
    feature6Title: "لوحة تحكم سهلة",
    feature6Desc: "تتبع إيراداتك وفواتيرك المدفوعة وغير المدفوعة بلمحة واحدة.",
    pricingTitle: "تسعير بسيط وشفاف",
    pricingSubtitle: "لا يوجد اشتراك شهري. ادفع فقط مقابل ما تستخدمه.",
    pricingCardTitle: "الدفع لكل فاتورة",
    pricingCardPrice: "1 رصيد / فاتورة",
    pricingCardPriceDetail: "(~ 2 درهم)",
    pricingFeature1: "5 أرصدة مجانية عند التسجيل",
    pricingFeature2: "لا توجد رسوم خفية",
    pricingFeature3: "اشترِ الأرصدة حسب الحاجة",
    pricingFeature4: "جميع الميزات متضمنة",
    ctaTitle: "هل أنت مستعد لتبسيط عملية الفوترة؟",
    ctaSubtitle: "أنشئ حسابًا وأرسل فاتورتك الأولى في دقائق.",
    footerText: "© 2024 Invoice.ma. جميع الحقوق محفوظة. أداة مصممة لرواد الأعمال المغاربة.",
    
    // Legal
    termsOfService: "شروط الاستخدام",
    privacyPolicy: "سياسة الخصوصية",
    termsTitle: "شروط الاستخدام",
    termsContent: `<p>آخر تحديث: [التاريخ]</p><p>مرحبًا بك في Invoice.ma. باستخدامك لخدمتنا، فإنك توافق على هذه الشروط. يرجى قراءتها بعناية.</p><strong>1. استخدام الخدمة</strong><p>يجب عليك اتباع جميع السياسات المتاحة لك ضمن الخدمة. لا تسيء استخدام خدماتنا. لا يجوز لك استخدام خدماتنا إلا وفقًا لما يسمح به القانون.</p><strong>2. حسابك على Invoice.ma</strong><p>لحماية حسابك، حافظ على سرية كلمة المرور الخاصة بك. أنت مسؤول عن النشاط الذي يحدث على حسابك أو من خلاله.</p><strong>3. التعديلات وإنهاء خدماتنا</strong><p>نحن نغير خدماتنا ونحسنها باستمرار. قد نضيف أو نزيل وظائف أو ميزات، وقد نعلق خدمة أو نوقفها تمامًا.</p>`,
    privacyTitle: "سياسة الخصوصية",
    privacyContent: `<p>آخر تحديث: [التاريخ]</p><p>تشرح سياسة الخصوصية هذه كيف يقوم Invoice.ma بجمع واستخدام وحماية معلوماتك الشخصية.</p><strong>1. المعلومات التي نجمعها</strong><p>نحن نجمع المعلومات التي تقدمها لنا مباشرة، مثل معلومات حسابك وتفاصيل الفواتير التي تنشئها. نستخدم التخزين المحلي للمتصفح الخاص بك للحفاظ على بياناتك؛ لا يتم إرسال أي بيانات فاتورة إلى خوادمنا.</p><strong>2. كيف نستخدم المعلومات</strong><p>نستخدم المعلومات التي نجمعها لتوفير خدماتنا وصيانتها وتحسينها.</p><strong>3. مشاركة المعلومات</strong><p>نحن لا نشارك معلوماتك الشخصية مع الشركات أو المنظمات أو الأفراد خارج Invoice.ma.</p>`,

    // WhatsApp
    sendByWhatsApp: "إرسال عبر واتساب",
    whatsAppModalTitle: "مشاركة الفاتورة عبر واتساب",
    whatsAppMessage: "رسالة واتساب",
    clientPhoneNumber: "رقم هاتف العميل",
    whatsAppMessageTemplate: "مرحباً {clientName}،\n\nتجدون أدناه رابط فاتورتكم رقم {invoiceNumber} بمبلغ إجمالي {totalAmount}.\n\n{invoiceLink}\n\nمع خالص التقدير،\n{companyName}",
    send: "إرسال",

    // Admin Panel v2
    admin_dashboard: "لوحة تحكم المشرف",
    admin_users: "المستخدمون",
    admin_appearance: "المظهر",
    admin_notifications: "الإشعارات",
    admin_settings: "الإعدادات العامة",
    admin_security: "الأمان",
    totalUsers: "إجمالي المستخدمين",
    totalCreditsDistributed: "إجمالي الأرصدة الموزعة",
    customizeAppearance: "تخصيص المظهر",
    primaryColor: "اللون الأساسي",
    appLogo: "شعار التطبيق",
    saveChanges: "حفظ التغييرات",
    globalNotification: "إشعار عام",
    notificationMessage: "رسالة الإشعار",
    notificationStatus: "حالة الإشعار",
    active: "نشط",
    inactive: "غير نشط",
    updateNotification: "تحديث الإشعار",
    
    // Admin Security
    changeAdminPassword: "تغيير كلمة مرور المشرف",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    passwordChangedSuccess: "تم تغيير كلمة المرور بنجاح!",
    passwordsDoNotMatch: "كلمتا المرور غير متطابقتين.",
    
    // Admin General Settings
    userRegistration: "تسجيل المستخدمين",
    allowNewRegistrations: "السماح بالتسجيلات الجديدة",
    enabled: "مفعل",
    disabled: "معطل",
    initialCreditsForNewUsers: "الأرصدة الأولية للمستخدمين الجدد",
    defaultInvoiceSettings: "إعدادات الفاتورة الافتراضية",
    defaultCurrency: "العملة الافتراضية",
    smtpHost: "مضيف SMTP",
    smtpPort: "منفذ SMTP",
    smtpUser: "مستخدم SMTP",
    smtpPassword: "كلمة مرور SMTP",
    smtpEncryption: "التشفير",

    // Admin Appearance v2
    advancedAppearanceSettings: "إعدادات المظهر المتقدمة",
    colorMode: "وضع الألوان",
    light: "فاتح",
    dark: "داكن",
    system: "النظام",
    fontFamily: "نوع الخط",
    borderRadius: "استدارة الحواف",
    radius_none: "بدون",
    radius_sm: "صغير",
    radius_md: "متوسط",
    radius_lg: "كبير",
    favicon: "أيقونة المتصفح (Favicon)",
    layoutDensity: "كثافة الواجهة",
    density_comfortable: "مريحة",
    density_compact: "مدمجة",


    // Invoice Edit cost
    editCostFree: "تعديلك الأول لهذه الفاتورة مجاني.",
    editCostCharged: "هذا التعديل سيكلف 1 رصيد. الأرصدة المتبقية لديك: {credits}.",
    editFailedNoCredits: "ليس لديك أرصدة كافية لحفظ هذه التغييرات. يرجى شراء المزيد من الأرصدة.",
    invoiceNumberReadonly: "لا يمكن تغيير رقم الفاتورة بعد إنشائها للحفاظ على سلامة السجلات.",

    // Feature Set 1: Analytics
    cashFlowForecast: "توقعات التدفق النقدي",
    timeframe: "الفترة الزمنية",
    next30days: "الـ 30 يومًا القادمة",
    next60days: "الـ 60 يومًا القادمة",
    next90days: "الـ 90 يومًا القادمة",
    projectedIncome: "الدخل المتوقع",
    noUpcomingIncome: "لا يوجد دخل متوقع للفترة المحددة.",
    tvaCollectionReport: "تقرير تحصيل الضريبة على القيمة المضافة",
    selectPeriod: "اختر فترة",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    totalInvoicedTVA: "إجمالي ضريبة القيمة المضافة المفوتَرة",
    totalCollectedTVA: "إجمالي ضريبة القيمة المضافة المحصَّلة",
    performanceDashboard: "لوحة مؤشرات الأداء",
    topClients: "أفضل العملاء",
    topProductsServices: "أفضل المنتجات/الخدمات",
    clientPaymentHabits: "عادات الدفع لدى العملاء",
    avgPaymentDays: "متوسط أيام الدفع",
    daysLate: "أيام تأخير",
    paidOnTime: "دُفع في الوقت المحدد",
    paidEarly: "أيام مبكراً",
    noData: "لا توجد بيانات متاحة.",
    serviceDescription: "وصف الخدمة",

    // Feature Set 2: Client Portal & Multi-currency
    clientPortal: "بوابة العميل",
    accountStatement: "كشف حساب",
    outstandingBalance: "الرصيد المستحق",
    payNow: "ادفع الآن",
    sendMessage: "إرسال رسالة",
    messageSentSuccess: "تم إرسال الرسالة بنجاح!",
    typeYourMessage: "اكتب رسالتك هنا...",
    totalInvoices_portal: "إجمالي الفواتير",
    totalPaid_portal: "إجمالي المدفوع",
    exchangeRate: "سعر الصرف",
    exchangeRateNote: "سعر الصرف ({from}/{to}) بتاريخ {date}: {rate}",
    
    // Auto-entrepreneur & TVA Declaration
    businessProfile: "الملف التجاري",
    businessType: "نوع الشركة",
    type_company: "شركة",
    "type_auto-entrepreneur": "مقاول ذاتي",
    autoEntrepreneurType: "نوع النشاط (مقاول ذاتي)",
    ae_services: "تقديم الخدمات",
    ae_industrial: "أنشطة صناعية",
    ae_commercial: "أنشطة تجارية",
    ae_artisanal: "أنشطة حرفية",
    aeRevenueTracker: "متتبع رقم المعاملات (مقاول ذاتي)",
    annualRevenue: "رقم المعاملات السنوي (المُحصَّل)",
    revenueCap: "السقف القانوني",
    tvaNotApplicable: "الضريبة على القيمة المضافة غير مطبقة - المادة 293 B من CGI",
    invoiceCustomization: "تخصيص الفواتير",
    invoiceNumberPrefix: "بادئة رقم الفاتورة",
    invoicePrefixPlaceholder: "مثال: FACT-{YEAR}-",
    defaultInvoiceNotes: "ملاحظات افتراضية على الفاتورة",
    tvaDeclaration: "إقرار الضريبة على القيمة المضافة",
    exportSalesReport: "تصدير تقرير المبيعات (CSV)",
    exportCollectionsReport: "تصدير تقرير التحصيلات (CSV)",

    // Admin User Edit
    editUserTitle: "تعديل المستخدم",
    userSettings: "إعدادات المستخدم",
    resetUserPassword: "إعادة تعيين كلمة المرور",
    resetPasswordConfirmation: "هل أنت متأكد من إعادة تعيين كلمة مرور هذا المستخدم؟ سيتم إنشاء كلمة مرور مؤقتة جديدة.",
    passwordResetSuccess: "تمت إعادة تعيين كلمة مرور المستخدم إلى 'password123'.",
  },
};